language: objective-c
osx_image: xcode8
env:
  global:
  - PROJECT=BrickKit.xcodeproj
  - IOS_FRAMEWORK_SCHEME="BrickKit"
  - TVOS_FRAMEWORK_SCHEME="BrickKit-tvOS"
  - IOS_SDK=iphonesimulator10.0
  - TVOS_SDK=appletvsimulator10.0
  - IOS_EXAMPLE_SCHEME="BrickApp-iOS"
  - TVOS_EXAMPLE_SCHEME="BrickApp-tvOS"
  matrix:

    - DESTINATION="OS=10.0,name=iPhone 7 Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="YES"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test