language: objective-c
osx_image: xcode8
env:
  global:
  - WORKSPACE=BrickKit.xcworkspace
  - IOS_FRAMEWORK_SCHEME="BrickKit"
  - TVOS_FRAMEWORK_SCHEME="BrickKit-tvOS"
  - IOS_SDK=iphonesimulator10.0
  - TVOS_SDK=appletvsimulator10.0
  - IOS_EXAMPLE_SCHEME="BrickApp-iOS"
  - TVOS_EXAMPLE_SCHEME="BrickApp-tvOS"
  matrix:

    - DESTINATION="OS=10.0,name=iPhone 7 Plus"     SCHEME="$IOS_EXAMPLE_SCHEME"     SDK="$IOS_SDK"     POD_LINT="YES"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES build test | xcpretty;

  # - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES build test | xcpretty;

after_success:
  - bash <(curl -s https://codecov.io/bash)